source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!

target 'TextureExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'

  pod 'Moya/RxSwift' # https://github.com/Moya/Moya
  pod 'Moya-ObjectMapper/RxSwift' # https://github.com/bmoliveira/Moya-ObjectMapper

  pod 'Texture'
  pod 'TextureSwiftSupport'
  pod 'Texture/PINRemoteImage'
    
  pod "TypedTextAttributes"
  pod "GlossButtonNode"
  pod "Reveal-SDK"
  pod "StorybookKit"
  pod "StorybookUI"
  pod "StorybookKitTextureSupport"
  pod "EasyPeasy"
  
  pod 'Localize-Swift'

  # UI Test Tools
  pod 'LookinServer', :configurations => ['Debug']

end

post_install do |installer|
  # targets
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
