# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureDemo
  
  pod 'Texture'
  pod 'TextureSwiftSupport'
  pod 'Texture/PINRemoteImage'
  
  # UI Test Tools
  pod 'LookinServer', :configurations => ['Debug']

end
