# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureDemo
  
  pod 'Texture'
  pod 'TextureSwiftSupport'
  pod 'Texture/PINRemoteImage'
    
  pod "TypedTextAttributes"
  pod "GlossButtonNode"
  pod "Reveal-SDK"
  pod "StorybookKit"
  pod "StorybookUI"
  pod "StorybookKitTextureSupport"
  pod "EasyPeasy"

  # UI Test Tools
  pod 'LookinServer', :configurations => ['Debug']

end
